# door — la herse se lève quand la propriété `open` est vraie
class Herse extends Behaviour {
    let base = nil
    let lift = 0

    fn on_start() {
        this.base = this.position()
    }

    fn on_update(dt) {
        if (this.prop("open") == true and this.lift < 1) {
            this.lift = math.min(1, this.lift + dt * 0.7)
            this.set_position(this.base[0], this.base[1] + this.lift * 3.8, this.base[2])
        }
    }
}
