# skeleton — patrouille entre patrol_min et patrol_max (axe Z)
let heading = map()

fn on_start(self) { heading[self] = 1 }

fn on_update(self, dt) {
    let p = object.position(self)
    let lo = node.prop(self, "patrol_min")
    let hi = node.prop(self, "patrol_max")
    let z = p[2] + heading[self] * 1.2 * dt
    if (z > hi) {
        z = hi
        heading[self] = -1
    }
    if (z < lo) {
        z = lo
        heading[self] = 1
    }
    object.set_position(self, p[0], p[1], z)
    let facing = 0
    if (heading[self] < 0) { facing = 180 }
    object.set_rotation(self, 0, facing, math.sin(editor.time() * 6) * 4)
}
